server:
  shutdown: graceful
  compression:
    enabled: true
    mime-types: application/json

spring:
  application:
    name: ms-example
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

