spring:
  application:
    name: ms-sample-app
  profiles:
    active: ${APP_ACTIVE_PROFILE:local}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        default_schema: ${APP_POSTGRESQL_SCHEMA:public}
    database: POSTGRESQL
  datasource:
    url: ${APP_POSTGRESQL_URL:jdbc:postgresql://localhost:5432/sample}
    username: ${APP_POSTGRESQL_USER_RW:test}
    password: ${APP_POSTGRESQL_PASSWORD_RW:sample}
    driverClassName: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog-master.xml
  cloud:
    function:
      definition: consumer-sample-command;
    stream:
      bindings:
        producer-sample-event:
          destination: event.sample
          content-type: application/json
          producer:
            useNativeEncoding: true
        producer-sample-command:
          destination: command.process.sample
          content-type: application/json
          producer:
            useNativeEncoding: true
        consumer-sample-command-in-0:
          destination: command.process.sample
          content-type: application/json
          group: sample-app
          consumer:
            use-native-decoding: true
            concurrency: 3


      kafka:
        bindings:
          #By default, the Spring cloud retries for a maximum of 3 attempts with one second initial delay,
          # 2.0 multiplier with each back off with a max delay of 10 seconds.
          consumer-sample-command-in-0:
            consumer:
              enableDlq: true
              dlq-partitions: 1
              dlqName: private.command.process.sample-dlq
